/*
 * File: /app/routes/api/v1/git/repo-list.ts
 * Project: portfolio
 * Created: Thursday, 8th December 2022
 * Author: Denpex
 * -----
 * Copyright 2022, ©Mehdi Rashadatjou
 * -----
 */

import { json, LoaderFunction } from "@remix-run/node";
import { mapRepoList } from "~/mapper/git.mapper";
import { fakeFetch } from "~/utils/helper.server";
import { BASE_URL, HTTP_HEADERS } from "~/constants/git";

// - Const
const MOCK = `
[
  {
    "id": 157562990,
    "node_id": "MDEwOlJlcG9zaXRvcnkxNTc1NjI5OTA=",
    "name": "advanced-demos",
    "full_name": "flowplayer/advanced-demos",
    "private": false,
    "owner": {
      "login": "flowplayer",
      "id": 266304,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjI2NjMwNA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/266304?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/flowplayer",
      "html_url": "https://github.com/flowplayer",
      "followers_url": "https://api.github.com/users/flowplayer/followers",
      "following_url": "https://api.github.com/users/flowplayer/following{/other_user}",
      "gists_url": "https://api.github.com/users/flowplayer/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/flowplayer/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/flowplayer/subscriptions",
      "organizations_url": "https://api.github.com/users/flowplayer/orgs",
      "repos_url": "https://api.github.com/users/flowplayer/repos",
      "events_url": "https://api.github.com/users/flowplayer/events{/privacy}",
      "received_events_url": "https://api.github.com/users/flowplayer/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "html_url": "https://github.com/flowplayer/advanced-demos",
    "description": "advanced demos for native & cloud players",
    "fork": false,
    "url": "https://api.github.com/repos/flowplayer/advanced-demos",
    "forks_url": "https://api.github.com/repos/flowplayer/advanced-demos/forks",
    "keys_url": "https://api.github.com/repos/flowplayer/advanced-demos/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/flowplayer/advanced-demos/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/flowplayer/advanced-demos/teams",
    "hooks_url": "https://api.github.com/repos/flowplayer/advanced-demos/hooks",
    "issue_events_url": "https://api.github.com/repos/flowplayer/advanced-demos/issues/events{/number}",
    "events_url": "https://api.github.com/repos/flowplayer/advanced-demos/events",
    "assignees_url": "https://api.github.com/repos/flowplayer/advanced-demos/assignees{/user}",
    "branches_url": "https://api.github.com/repos/flowplayer/advanced-demos/branches{/branch}",
    "tags_url": "https://api.github.com/repos/flowplayer/advanced-demos/tags",
    "blobs_url": "https://api.github.com/repos/flowplayer/advanced-demos/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/flowplayer/advanced-demos/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/flowplayer/advanced-demos/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/flowplayer/advanced-demos/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/flowplayer/advanced-demos/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/flowplayer/advanced-demos/languages",
    "stargazers_url": "https://api.github.com/repos/flowplayer/advanced-demos/stargazers",
    "contributors_url": "https://api.github.com/repos/flowplayer/advanced-demos/contributors",
    "subscribers_url": "https://api.github.com/repos/flowplayer/advanced-demos/subscribers",
    "subscription_url": "https://api.github.com/repos/flowplayer/advanced-demos/subscription",
    "commits_url": "https://api.github.com/repos/flowplayer/advanced-demos/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/flowplayer/advanced-demos/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/flowplayer/advanced-demos/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/flowplayer/advanced-demos/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/flowplayer/advanced-demos/contents/{+path}",
    "compare_url": "https://api.github.com/repos/flowplayer/advanced-demos/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/flowplayer/advanced-demos/merges",
    "archive_url": "https://api.github.com/repos/flowplayer/advanced-demos/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/flowplayer/advanced-demos/downloads",
    "issues_url": "https://api.github.com/repos/flowplayer/advanced-demos/issues{/number}",
    "pulls_url": "https://api.github.com/repos/flowplayer/advanced-demos/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/flowplayer/advanced-demos/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/flowplayer/advanced-demos/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/flowplayer/advanced-demos/labels{/name}",
    "releases_url": "https://api.github.com/repos/flowplayer/advanced-demos/releases{/id}",
    "deployments_url": "https://api.github.com/repos/flowplayer/advanced-demos/deployments",
    "created_at": "2018-11-14T14:43:14Z",
    "updated_at": "2022-08-30T08:57:54Z",
    "pushed_at": "2022-12-06T12:30:32Z",
    "git_url": "git://github.com/flowplayer/advanced-demos.git",
    "ssh_url": "git@github.com:flowplayer/advanced-demos.git",
    "clone_url": "https://github.com/flowplayer/advanced-demos.git",
    "svn_url": "https://github.com/flowplayer/advanced-demos",
    "homepage": null,
    "size": 1345,
    "stargazers_count": 5,
    "watchers_count": 5,
    "language": "Shell",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "has_discussions": false,
    "forks_count": 5,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 3,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 5,
    "open_issues": 3,
    "watchers": 5,
    "default_branch": "master",
    "permissions": {
      "admin": false,
      "maintain": false,
      "push": true,
      "triage": true,
      "pull": true
    }
  },
  {
    "id": 310026097,
    "node_id": "MDEwOlJlcG9zaXRvcnkzMTAwMjYwOTc=",
    "name": "react-flowplayer",
    "full_name": "flowplayer/react-flowplayer",
    "private": false,
    "owner": {
      "login": "flowplayer",
      "id": 266304,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjI2NjMwNA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/266304?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/flowplayer",
      "html_url": "https://github.com/flowplayer",
      "followers_url": "https://api.github.com/users/flowplayer/followers",
      "following_url": "https://api.github.com/users/flowplayer/following{/other_user}",
      "gists_url": "https://api.github.com/users/flowplayer/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/flowplayer/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/flowplayer/subscriptions",
      "organizations_url": "https://api.github.com/users/flowplayer/orgs",
      "repos_url": "https://api.github.com/users/flowplayer/repos",
      "events_url": "https://api.github.com/users/flowplayer/events{/privacy}",
      "received_events_url": "https://api.github.com/users/flowplayer/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "html_url": "https://github.com/flowplayer/react-flowplayer",
    "description": "Flowplayer React Component",
    "fork": false,
    "url": "https://api.github.com/repos/flowplayer/react-flowplayer",
    "forks_url": "https://api.github.com/repos/flowplayer/react-flowplayer/forks",
    "keys_url": "https://api.github.com/repos/flowplayer/react-flowplayer/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/flowplayer/react-flowplayer/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/flowplayer/react-flowplayer/teams",
    "hooks_url": "https://api.github.com/repos/flowplayer/react-flowplayer/hooks",
    "issue_events_url": "https://api.github.com/repos/flowplayer/react-flowplayer/issues/events{/number}",
    "events_url": "https://api.github.com/repos/flowplayer/react-flowplayer/events",
    "assignees_url": "https://api.github.com/repos/flowplayer/react-flowplayer/assignees{/user}",
    "branches_url": "https://api.github.com/repos/flowplayer/react-flowplayer/branches{/branch}",
    "tags_url": "https://api.github.com/repos/flowplayer/react-flowplayer/tags",
    "blobs_url": "https://api.github.com/repos/flowplayer/react-flowplayer/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/flowplayer/react-flowplayer/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/flowplayer/react-flowplayer/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/flowplayer/react-flowplayer/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/flowplayer/react-flowplayer/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/flowplayer/react-flowplayer/languages",
    "stargazers_url": "https://api.github.com/repos/flowplayer/react-flowplayer/stargazers",
    "contributors_url": "https://api.github.com/repos/flowplayer/react-flowplayer/contributors",
    "subscribers_url": "https://api.github.com/repos/flowplayer/react-flowplayer/subscribers",
    "subscription_url": "https://api.github.com/repos/flowplayer/react-flowplayer/subscription",
    "commits_url": "https://api.github.com/repos/flowplayer/react-flowplayer/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/flowplayer/react-flowplayer/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/flowplayer/react-flowplayer/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/flowplayer/react-flowplayer/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/flowplayer/react-flowplayer/contents/{+path}",
    "compare_url": "https://api.github.com/repos/flowplayer/react-flowplayer/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/flowplayer/react-flowplayer/merges",
    "archive_url": "https://api.github.com/repos/flowplayer/react-flowplayer/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/flowplayer/react-flowplayer/downloads",
    "issues_url": "https://api.github.com/repos/flowplayer/react-flowplayer/issues{/number}",
    "pulls_url": "https://api.github.com/repos/flowplayer/react-flowplayer/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/flowplayer/react-flowplayer/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/flowplayer/react-flowplayer/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/flowplayer/react-flowplayer/labels{/name}",
    "releases_url": "https://api.github.com/repos/flowplayer/react-flowplayer/releases{/id}",
    "deployments_url": "https://api.github.com/repos/flowplayer/react-flowplayer/deployments",
    "created_at": "2020-11-04T14:26:36Z",
    "updated_at": "2022-11-19T08:31:37Z",
    "pushed_at": "2022-11-18T00:44:48Z",
    "git_url": "git://github.com/flowplayer/react-flowplayer.git",
    "ssh_url": "git@github.com:flowplayer/react-flowplayer.git",
    "clone_url": "https://github.com/flowplayer/react-flowplayer.git",
    "svn_url": "https://github.com/flowplayer/react-flowplayer",
    "homepage": null,
    "size": 479,
    "stargazers_count": 2,
    "watchers_count": 2,
    "language": "TypeScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": true,
    "forks_count": 3,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 3,
    "license": {
      "key": "mit",
      "name": "MIT License",
      "spdx_id": "MIT",
      "url": "https://api.github.com/licenses/mit",
      "node_id": "MDc6TGljZW5zZTEz"
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 3,
    "open_issues": 3,
    "watchers": 2,
    "default_branch": "main",
    "permissions": {
      "admin": false,
      "maintain": false,
      "push": true,
      "triage": true,
      "pull": true
    }
  },
  {
    "id": 390131856,
    "node_id": "MDEwOlJlcG9zaXRvcnkzOTAxMzE4NTY=",
    "name": "flowplayer-ios",
    "full_name": "flowplayer/flowplayer-ios",
    "private": false,
    "owner": {
      "login": "flowplayer",
      "id": 266304,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjI2NjMwNA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/266304?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/flowplayer",
      "html_url": "https://github.com/flowplayer",
      "followers_url": "https://api.github.com/users/flowplayer/followers",
      "following_url": "https://api.github.com/users/flowplayer/following{/other_user}",
      "gists_url": "https://api.github.com/users/flowplayer/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/flowplayer/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/flowplayer/subscriptions",
      "organizations_url": "https://api.github.com/users/flowplayer/orgs",
      "repos_url": "https://api.github.com/users/flowplayer/repos",
      "events_url": "https://api.github.com/users/flowplayer/events{/privacy}",
      "received_events_url": "https://api.github.com/users/flowplayer/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "html_url": "https://github.com/flowplayer/flowplayer-ios",
    "description": "Public repository for the Flowplayer iOS SDK",
    "fork": false,
    "url": "https://api.github.com/repos/flowplayer/flowplayer-ios",
    "forks_url": "https://api.github.com/repos/flowplayer/flowplayer-ios/forks",
    "keys_url": "https://api.github.com/repos/flowplayer/flowplayer-ios/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/flowplayer/flowplayer-ios/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/flowplayer/flowplayer-ios/teams",
    "hooks_url": "https://api.github.com/repos/flowplayer/flowplayer-ios/hooks",
    "issue_events_url": "https://api.github.com/repos/flowplayer/flowplayer-ios/issues/events{/number}",
    "events_url": "https://api.github.com/repos/flowplayer/flowplayer-ios/events",
    "assignees_url": "https://api.github.com/repos/flowplayer/flowplayer-ios/assignees{/user}",
    "branches_url": "https://api.github.com/repos/flowplayer/flowplayer-ios/branches{/branch}",
    "tags_url": "https://api.github.com/repos/flowplayer/flowplayer-ios/tags",
    "blobs_url": "https://api.github.com/repos/flowplayer/flowplayer-ios/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/flowplayer/flowplayer-ios/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/flowplayer/flowplayer-ios/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/flowplayer/flowplayer-ios/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/flowplayer/flowplayer-ios/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/flowplayer/flowplayer-ios/languages",
    "stargazers_url": "https://api.github.com/repos/flowplayer/flowplayer-ios/stargazers",
    "contributors_url": "https://api.github.com/repos/flowplayer/flowplayer-ios/contributors",
    "subscribers_url": "https://api.github.com/repos/flowplayer/flowplayer-ios/subscribers",
    "subscription_url": "https://api.github.com/repos/flowplayer/flowplayer-ios/subscription",
    "commits_url": "https://api.github.com/repos/flowplayer/flowplayer-ios/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/flowplayer/flowplayer-ios/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/flowplayer/flowplayer-ios/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/flowplayer/flowplayer-ios/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/flowplayer/flowplayer-ios/contents/{+path}",
    "compare_url": "https://api.github.com/repos/flowplayer/flowplayer-ios/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/flowplayer/flowplayer-ios/merges",
    "archive_url": "https://api.github.com/repos/flowplayer/flowplayer-ios/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/flowplayer/flowplayer-ios/downloads",
    "issues_url": "https://api.github.com/repos/flowplayer/flowplayer-ios/issues{/number}",
    "pulls_url": "https://api.github.com/repos/flowplayer/flowplayer-ios/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/flowplayer/flowplayer-ios/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/flowplayer/flowplayer-ios/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/flowplayer/flowplayer-ios/labels{/name}",
    "releases_url": "https://api.github.com/repos/flowplayer/flowplayer-ios/releases{/id}",
    "deployments_url": "https://api.github.com/repos/flowplayer/flowplayer-ios/deployments",
    "created_at": "2021-07-27T21:29:14Z",
    "updated_at": "2022-02-09T16:09:51Z",
    "pushed_at": "2022-11-29T09:51:23Z",
    "git_url": "git://github.com/flowplayer/flowplayer-ios.git",
    "ssh_url": "git@github.com:flowplayer/flowplayer-ios.git",
    "clone_url": "https://github.com/flowplayer/flowplayer-ios.git",
    "svn_url": "https://github.com/flowplayer/flowplayer-ios",
    "homepage": null,
    "size": 283,
    "stargazers_count": 1,
    "watchers_count": 1,
    "language": "Objective-C",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 1,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": {
      "key": "mit",
      "name": "MIT License",
      "spdx_id": "MIT",
      "url": "https://api.github.com/licenses/mit",
      "node_id": "MDc6TGljZW5zZTEz"
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 1,
    "open_issues": 0,
    "watchers": 1,
    "default_branch": "main",
    "permissions": {
      "admin": true,
      "maintain": true,
      "push": true,
      "triage": true,
      "pull": true
    }
  },
  {
    "id": 429571916,
    "node_id": "R_kgDOGZq_TA",
    "name": "flowplayer-tvos",
    "full_name": "flowplayer/flowplayer-tvos",
    "private": false,
    "owner": {
      "login": "flowplayer",
      "id": 266304,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjI2NjMwNA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/266304?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/flowplayer",
      "html_url": "https://github.com/flowplayer",
      "followers_url": "https://api.github.com/users/flowplayer/followers",
      "following_url": "https://api.github.com/users/flowplayer/following{/other_user}",
      "gists_url": "https://api.github.com/users/flowplayer/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/flowplayer/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/flowplayer/subscriptions",
      "organizations_url": "https://api.github.com/users/flowplayer/orgs",
      "repos_url": "https://api.github.com/users/flowplayer/repos",
      "events_url": "https://api.github.com/users/flowplayer/events{/privacy}",
      "received_events_url": "https://api.github.com/users/flowplayer/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "html_url": "https://github.com/flowplayer/flowplayer-tvos",
    "description": "Public repository for the Flowplayer tvOS SDK",
    "fork": false,
    "url": "https://api.github.com/repos/flowplayer/flowplayer-tvos",
    "forks_url": "https://api.github.com/repos/flowplayer/flowplayer-tvos/forks",
    "keys_url": "https://api.github.com/repos/flowplayer/flowplayer-tvos/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/flowplayer/flowplayer-tvos/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/flowplayer/flowplayer-tvos/teams",
    "hooks_url": "https://api.github.com/repos/flowplayer/flowplayer-tvos/hooks",
    "issue_events_url": "https://api.github.com/repos/flowplayer/flowplayer-tvos/issues/events{/number}",
    "events_url": "https://api.github.com/repos/flowplayer/flowplayer-tvos/events",
    "assignees_url": "https://api.github.com/repos/flowplayer/flowplayer-tvos/assignees{/user}",
    "branches_url": "https://api.github.com/repos/flowplayer/flowplayer-tvos/branches{/branch}",
    "tags_url": "https://api.github.com/repos/flowplayer/flowplayer-tvos/tags",
    "blobs_url": "https://api.github.com/repos/flowplayer/flowplayer-tvos/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/flowplayer/flowplayer-tvos/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/flowplayer/flowplayer-tvos/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/flowplayer/flowplayer-tvos/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/flowplayer/flowplayer-tvos/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/flowplayer/flowplayer-tvos/languages",
    "stargazers_url": "https://api.github.com/repos/flowplayer/flowplayer-tvos/stargazers",
    "contributors_url": "https://api.github.com/repos/flowplayer/flowplayer-tvos/contributors",
    "subscribers_url": "https://api.github.com/repos/flowplayer/flowplayer-tvos/subscribers",
    "subscription_url": "https://api.github.com/repos/flowplayer/flowplayer-tvos/subscription",
    "commits_url": "https://api.github.com/repos/flowplayer/flowplayer-tvos/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/flowplayer/flowplayer-tvos/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/flowplayer/flowplayer-tvos/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/flowplayer/flowplayer-tvos/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/flowplayer/flowplayer-tvos/contents/{+path}",
    "compare_url": "https://api.github.com/repos/flowplayer/flowplayer-tvos/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/flowplayer/flowplayer-tvos/merges",
    "archive_url": "https://api.github.com/repos/flowplayer/flowplayer-tvos/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/flowplayer/flowplayer-tvos/downloads",
    "issues_url": "https://api.github.com/repos/flowplayer/flowplayer-tvos/issues{/number}",
    "pulls_url": "https://api.github.com/repos/flowplayer/flowplayer-tvos/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/flowplayer/flowplayer-tvos/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/flowplayer/flowplayer-tvos/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/flowplayer/flowplayer-tvos/labels{/name}",
    "releases_url": "https://api.github.com/repos/flowplayer/flowplayer-tvos/releases{/id}",
    "deployments_url": "https://api.github.com/repos/flowplayer/flowplayer-tvos/deployments",
    "created_at": "2021-11-18T20:34:37Z",
    "updated_at": "2022-02-10T09:46:22Z",
    "pushed_at": "2022-11-14T13:32:58Z",
    "git_url": "git://github.com/flowplayer/flowplayer-tvos.git",
    "ssh_url": "git@github.com:flowplayer/flowplayer-tvos.git",
    "clone_url": "https://github.com/flowplayer/flowplayer-tvos.git",
    "svn_url": "https://github.com/flowplayer/flowplayer-tvos",
    "homepage": "",
    "size": 16,
    "stargazers_count": 1,
    "watchers_count": 1,
    "language": "Swift",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 1,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": {
      "key": "mit",
      "name": "MIT License",
      "spdx_id": "MIT",
      "url": "https://api.github.com/licenses/mit",
      "node_id": "MDc6TGljZW5zZTEz"
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 1,
    "open_issues": 0,
    "watchers": 1,
    "default_branch": "main",
    "permissions": {
      "admin": true,
      "maintain": true,
      "push": true,
      "triage": true,
      "pull": true
    }
  },
  {
    "id": 436723014,
    "node_id": "R_kgDOGgfdRg",
    "name": "react.example-context-with-reducer",
    "full_name": "Denpex/react.example-context-with-reducer",
    "private": false,
    "owner": {
      "login": "Denpex",
      "id": 28106084,
      "node_id": "MDQ6VXNlcjI4MTA2MDg0",
      "avatar_url": "https://avatars.githubusercontent.com/u/28106084?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Denpex",
      "html_url": "https://github.com/Denpex",
      "followers_url": "https://api.github.com/users/Denpex/followers",
      "following_url": "https://api.github.com/users/Denpex/following{/other_user}",
      "gists_url": "https://api.github.com/users/Denpex/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Denpex/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Denpex/subscriptions",
      "organizations_url": "https://api.github.com/users/Denpex/orgs",
      "repos_url": "https://api.github.com/users/Denpex/repos",
      "events_url": "https://api.github.com/users/Denpex/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Denpex/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/Denpex/react.example-context-with-reducer",
    "description": "Small shop app that uses Context & Reducer hook",
    "fork": false,
    "url": "https://api.github.com/repos/Denpex/react.example-context-with-reducer",
    "forks_url": "https://api.github.com/repos/Denpex/react.example-context-with-reducer/forks",
    "keys_url": "https://api.github.com/repos/Denpex/react.example-context-with-reducer/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Denpex/react.example-context-with-reducer/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Denpex/react.example-context-with-reducer/teams",
    "hooks_url": "https://api.github.com/repos/Denpex/react.example-context-with-reducer/hooks",
    "issue_events_url": "https://api.github.com/repos/Denpex/react.example-context-with-reducer/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Denpex/react.example-context-with-reducer/events",
    "assignees_url": "https://api.github.com/repos/Denpex/react.example-context-with-reducer/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Denpex/react.example-context-with-reducer/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Denpex/react.example-context-with-reducer/tags",
    "blobs_url": "https://api.github.com/repos/Denpex/react.example-context-with-reducer/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Denpex/react.example-context-with-reducer/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Denpex/react.example-context-with-reducer/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Denpex/react.example-context-with-reducer/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Denpex/react.example-context-with-reducer/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Denpex/react.example-context-with-reducer/languages",
    "stargazers_url": "https://api.github.com/repos/Denpex/react.example-context-with-reducer/stargazers",
    "contributors_url": "https://api.github.com/repos/Denpex/react.example-context-with-reducer/contributors",
    "subscribers_url": "https://api.github.com/repos/Denpex/react.example-context-with-reducer/subscribers",
    "subscription_url": "https://api.github.com/repos/Denpex/react.example-context-with-reducer/subscription",
    "commits_url": "https://api.github.com/repos/Denpex/react.example-context-with-reducer/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Denpex/react.example-context-with-reducer/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Denpex/react.example-context-with-reducer/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Denpex/react.example-context-with-reducer/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Denpex/react.example-context-with-reducer/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Denpex/react.example-context-with-reducer/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Denpex/react.example-context-with-reducer/merges",
    "archive_url": "https://api.github.com/repos/Denpex/react.example-context-with-reducer/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Denpex/react.example-context-with-reducer/downloads",
    "issues_url": "https://api.github.com/repos/Denpex/react.example-context-with-reducer/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Denpex/react.example-context-with-reducer/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Denpex/react.example-context-with-reducer/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Denpex/react.example-context-with-reducer/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Denpex/react.example-context-with-reducer/labels{/name}",
    "releases_url": "https://api.github.com/repos/Denpex/react.example-context-with-reducer/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Denpex/react.example-context-with-reducer/deployments",
    "created_at": "2021-12-09T18:36:15Z",
    "updated_at": "2022-10-25T11:27:01Z",
    "pushed_at": "2021-12-09T18:38:28Z",
    "git_url": "git://github.com/Denpex/react.example-context-with-reducer.git",
    "ssh_url": "git@github.com:Denpex/react.example-context-with-reducer.git",
    "clone_url": "https://github.com/Denpex/react.example-context-with-reducer.git",
    "svn_url": "https://github.com/Denpex/react.example-context-with-reducer",
    "homepage": null,
    "size": 230,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "TypeScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main",
    "permissions": {
      "admin": true,
      "maintain": true,
      "push": true,
      "triage": true,
      "pull": true
    }
  },
  {
    "id": 533032468,
    "node_id": "R_kgDOH8VuFA",
    "name": "LocoPlugin",
    "full_name": "Denpex/LocoPlugin",
    "private": false,
    "owner": {
      "login": "Denpex",
      "id": 28106084,
      "node_id": "MDQ6VXNlcjI4MTA2MDg0",
      "avatar_url": "https://avatars.githubusercontent.com/u/28106084?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Denpex",
      "html_url": "https://github.com/Denpex",
      "followers_url": "https://api.github.com/users/Denpex/followers",
      "following_url": "https://api.github.com/users/Denpex/following{/other_user}",
      "gists_url": "https://api.github.com/users/Denpex/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Denpex/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Denpex/subscriptions",
      "organizations_url": "https://api.github.com/users/Denpex/orgs",
      "repos_url": "https://api.github.com/users/Denpex/repos",
      "events_url": "https://api.github.com/users/Denpex/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Denpex/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/Denpex/LocoPlugin",
    "description": "Localization plugin for Xcode powered by loco",
    "fork": false,
    "url": "https://api.github.com/repos/Denpex/LocoPlugin",
    "forks_url": "https://api.github.com/repos/Denpex/LocoPlugin/forks",
    "keys_url": "https://api.github.com/repos/Denpex/LocoPlugin/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Denpex/LocoPlugin/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Denpex/LocoPlugin/teams",
    "hooks_url": "https://api.github.com/repos/Denpex/LocoPlugin/hooks",
    "issue_events_url": "https://api.github.com/repos/Denpex/LocoPlugin/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Denpex/LocoPlugin/events",
    "assignees_url": "https://api.github.com/repos/Denpex/LocoPlugin/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Denpex/LocoPlugin/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Denpex/LocoPlugin/tags",
    "blobs_url": "https://api.github.com/repos/Denpex/LocoPlugin/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Denpex/LocoPlugin/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Denpex/LocoPlugin/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Denpex/LocoPlugin/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Denpex/LocoPlugin/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Denpex/LocoPlugin/languages",
    "stargazers_url": "https://api.github.com/repos/Denpex/LocoPlugin/stargazers",
    "contributors_url": "https://api.github.com/repos/Denpex/LocoPlugin/contributors",
    "subscribers_url": "https://api.github.com/repos/Denpex/LocoPlugin/subscribers",
    "subscription_url": "https://api.github.com/repos/Denpex/LocoPlugin/subscription",
    "commits_url": "https://api.github.com/repos/Denpex/LocoPlugin/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Denpex/LocoPlugin/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Denpex/LocoPlugin/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Denpex/LocoPlugin/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Denpex/LocoPlugin/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Denpex/LocoPlugin/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Denpex/LocoPlugin/merges",
    "archive_url": "https://api.github.com/repos/Denpex/LocoPlugin/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Denpex/LocoPlugin/downloads",
    "issues_url": "https://api.github.com/repos/Denpex/LocoPlugin/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Denpex/LocoPlugin/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Denpex/LocoPlugin/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Denpex/LocoPlugin/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Denpex/LocoPlugin/labels{/name}",
    "releases_url": "https://api.github.com/repos/Denpex/LocoPlugin/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Denpex/LocoPlugin/deployments",
    "created_at": "2022-09-05T19:24:09Z",
    "updated_at": "2022-11-15T12:50:30Z",
    "pushed_at": "2022-09-22T21:43:04Z",
    "git_url": "git://github.com/Denpex/LocoPlugin.git",
    "ssh_url": "git@github.com:Denpex/LocoPlugin.git",
    "clone_url": "https://github.com/Denpex/LocoPlugin.git",
    "svn_url": "https://github.com/Denpex/LocoPlugin",
    "homepage": null,
    "size": 434,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Swift",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": {
      "key": "mit",
      "name": "MIT License",
      "spdx_id": "MIT",
      "url": "https://api.github.com/licenses/mit",
      "node_id": "MDc6TGljZW5zZTEz"
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main",
    "permissions": {
      "admin": true,
      "maintain": true,
      "push": true,
      "triage": true,
      "pull": true
    }
  },
  {
    "id": 562243741,
    "node_id": "R_kgDOIYMonQ",
    "name": "themeit",
    "full_name": "Denpex/themeit",
    "private": false,
    "owner": {
      "login": "Denpex",
      "id": 28106084,
      "node_id": "MDQ6VXNlcjI4MTA2MDg0",
      "avatar_url": "https://avatars.githubusercontent.com/u/28106084?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Denpex",
      "html_url": "https://github.com/Denpex",
      "followers_url": "https://api.github.com/users/Denpex/followers",
      "following_url": "https://api.github.com/users/Denpex/following{/other_user}",
      "gists_url": "https://api.github.com/users/Denpex/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Denpex/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Denpex/subscriptions",
      "organizations_url": "https://api.github.com/users/Denpex/orgs",
      "repos_url": "https://api.github.com/users/Denpex/repos",
      "events_url": "https://api.github.com/users/Denpex/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Denpex/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/Denpex/themeit",
    "description": "Modern Web implementation for css theming",
    "fork": false,
    "url": "https://api.github.com/repos/Denpex/themeit",
    "forks_url": "https://api.github.com/repos/Denpex/themeit/forks",
    "keys_url": "https://api.github.com/repos/Denpex/themeit/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Denpex/themeit/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Denpex/themeit/teams",
    "hooks_url": "https://api.github.com/repos/Denpex/themeit/hooks",
    "issue_events_url": "https://api.github.com/repos/Denpex/themeit/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Denpex/themeit/events",
    "assignees_url": "https://api.github.com/repos/Denpex/themeit/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Denpex/themeit/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Denpex/themeit/tags",
    "blobs_url": "https://api.github.com/repos/Denpex/themeit/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Denpex/themeit/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Denpex/themeit/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Denpex/themeit/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Denpex/themeit/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Denpex/themeit/languages",
    "stargazers_url": "https://api.github.com/repos/Denpex/themeit/stargazers",
    "contributors_url": "https://api.github.com/repos/Denpex/themeit/contributors",
    "subscribers_url": "https://api.github.com/repos/Denpex/themeit/subscribers",
    "subscription_url": "https://api.github.com/repos/Denpex/themeit/subscription",
    "commits_url": "https://api.github.com/repos/Denpex/themeit/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Denpex/themeit/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Denpex/themeit/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Denpex/themeit/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Denpex/themeit/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Denpex/themeit/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Denpex/themeit/merges",
    "archive_url": "https://api.github.com/repos/Denpex/themeit/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Denpex/themeit/downloads",
    "issues_url": "https://api.github.com/repos/Denpex/themeit/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Denpex/themeit/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Denpex/themeit/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Denpex/themeit/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Denpex/themeit/labels{/name}",
    "releases_url": "https://api.github.com/repos/Denpex/themeit/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Denpex/themeit/deployments",
    "created_at": "2022-11-05T18:32:03Z",
    "updated_at": "2022-12-05T13:01:56Z",
    "pushed_at": "2022-12-05T13:03:49Z",
    "git_url": "git://github.com/Denpex/themeit.git",
    "ssh_url": "git@github.com:Denpex/themeit.git",
    "clone_url": "https://github.com/Denpex/themeit.git",
    "svn_url": "https://github.com/Denpex/themeit",
    "homepage": "",
    "size": 3759,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "TypeScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": {
      "key": "mit",
      "name": "MIT License",
      "spdx_id": "MIT",
      "url": "https://api.github.com/licenses/mit",
      "node_id": "MDc6TGljZW5zZTEz"
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "blazing",
      "browser-native",
      "css",
      "dark-theme",
      "javascript",
      "lightweight",
      "modern-web",
      "react",
      "small",
      "theme",
      "theming",
      "typescript"
    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main",
    "permissions": {
      "admin": true,
      "maintain": true,
      "push": true,
      "triage": true,
      "pull": true
    }
  },
  {
    "id": 573768991,
    "node_id": "R_kgDOIjMFHw",
    "name": "zkauth",
    "full_name": "Sulejman/zkauth",
    "private": false,
    "owner": {
      "login": "Sulejman",
      "id": 3107367,
      "node_id": "MDQ6VXNlcjMxMDczNjc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3107367?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Sulejman",
      "html_url": "https://github.com/Sulejman",
      "followers_url": "https://api.github.com/users/Sulejman/followers",
      "following_url": "https://api.github.com/users/Sulejman/following{/other_user}",
      "gists_url": "https://api.github.com/users/Sulejman/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Sulejman/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Sulejman/subscriptions",
      "organizations_url": "https://api.github.com/users/Sulejman/orgs",
      "repos_url": "https://api.github.com/users/Sulejman/repos",
      "events_url": "https://api.github.com/users/Sulejman/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Sulejman/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/Sulejman/zkauth",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/Sulejman/zkauth",
    "forks_url": "https://api.github.com/repos/Sulejman/zkauth/forks",
    "keys_url": "https://api.github.com/repos/Sulejman/zkauth/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Sulejman/zkauth/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Sulejman/zkauth/teams",
    "hooks_url": "https://api.github.com/repos/Sulejman/zkauth/hooks",
    "issue_events_url": "https://api.github.com/repos/Sulejman/zkauth/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Sulejman/zkauth/events",
    "assignees_url": "https://api.github.com/repos/Sulejman/zkauth/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Sulejman/zkauth/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Sulejman/zkauth/tags",
    "blobs_url": "https://api.github.com/repos/Sulejman/zkauth/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Sulejman/zkauth/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Sulejman/zkauth/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Sulejman/zkauth/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Sulejman/zkauth/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Sulejman/zkauth/languages",
    "stargazers_url": "https://api.github.com/repos/Sulejman/zkauth/stargazers",
    "contributors_url": "https://api.github.com/repos/Sulejman/zkauth/contributors",
    "subscribers_url": "https://api.github.com/repos/Sulejman/zkauth/subscribers",
    "subscription_url": "https://api.github.com/repos/Sulejman/zkauth/subscription",
    "commits_url": "https://api.github.com/repos/Sulejman/zkauth/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Sulejman/zkauth/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Sulejman/zkauth/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Sulejman/zkauth/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Sulejman/zkauth/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Sulejman/zkauth/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Sulejman/zkauth/merges",
    "archive_url": "https://api.github.com/repos/Sulejman/zkauth/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Sulejman/zkauth/downloads",
    "issues_url": "https://api.github.com/repos/Sulejman/zkauth/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Sulejman/zkauth/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Sulejman/zkauth/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Sulejman/zkauth/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Sulejman/zkauth/labels{/name}",
    "releases_url": "https://api.github.com/repos/Sulejman/zkauth/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Sulejman/zkauth/deployments",
    "created_at": "2022-12-03T11:26:31Z",
    "updated_at": "2022-12-03T11:26:31Z",
    "pushed_at": "2022-12-03T11:49:31Z",
    "git_url": "git://github.com/Sulejman/zkauth.git",
    "ssh_url": "git@github.com:Sulejman/zkauth.git",
    "clone_url": "https://github.com/Sulejman/zkauth.git",
    "svn_url": "https://github.com/Sulejman/zkauth",
    "homepage": null,
    "size": 3,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": null,
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main",
    "permissions": {
      "admin": false,
      "maintain": false,
      "push": true,
      "triage": true,
      "pull": true
    }
  }
]
`;

// - GET
export const loader: LoaderFunction = async () => {
  try {
    const url = new URL(`${BASE_URL}/user/repos`);
    url.searchParams.set("affiliation", "owner,collaborator");

    if (process.env.NODE_ENV === "development") {
      console.log("git/repos/mock");
      const res = await fakeFetch(Math.random() * 1000, MOCK);
      const cleanRes = mapRepoList(JSON.parse(res as string));
      return json(cleanRes, { status: 200 });
    }

    console.log("git/repos/prod");
    const res = await fetch(url, {
      method: "get",
      headers: HTTP_HEADERS,
    });
    const jsonRes = await res.json();
    const cleanRes = mapRepoList(jsonRes);
    return json(cleanRes, { status: 200 });
  } catch (error) {
    console.log("GIT ERROR:", error);
    return new Response("Failed", { status: 400 });
  }
};
